apiVersion: v1
kind: Service
metadata:
  name: bgg-db-svc
  namespace: workshop02
  labels:
    name: bgg-db-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bgg-db-pod
  ports:
  - name: mysql-port-svcs
    port: 3306
    targetPort: 3306
