apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-app-deployment
  namespace: workshop02
spec:
   replicas: 2
   selector:
      matchLabels:
        app.kubernetes.io/name: bgg-app-pod
   template:
    metadata:
      name: bgg-app-pod
      namespace: workshop02
      labels:
        app.kubernetes.io/name: bgg-app-pod
        app.kubernetes.io/version: "v1"
        owner: development
    spec:
      containers:
      - name: bgg-app-container
        image: stackupiss/bgg-app:v1
        imagePullPolicy: Always
        env:
        - name: APP_PORT
          value: "3000"
        - name: BGG_DB_HOST
          value: "bgg-db-svc.workshop02.svc.cluster.local"
        ports:  
        - name: bgg-app-port
          containerPort: 3000